### ISSUE TITLE
delete docker challenge failed [a foreign key constraint fails]

### ISSUE THREAD

**Issue by hitfzyangdianshi** [pwncollege/dojo#14]
http://sqlalche.me/e/gkpj

```
ctfd_1   | ERROR [CTFd] Exception on /api/v1/challenges/1 [DELETE]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`docker_challenges`, CONSTRAINT `docker_challenges_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')
ctfd_1   | 
ctfd_1   | The above exception was the direct cause of the following exception:
ctfd_1   | 
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
ctfd_1   |     resp = resource(*args, **kwargs)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
ctfd_1   |     return self.dispatch_request(*args, **kwargs)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
ctfd_1   |     resp = meth(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 110, in admins_only_wrapper
ctfd_1   |     return f(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/api/v1/challenges.py", line 444, in delete
ctfd_1   |     chal_class.delete(challenge)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/challenges/__init__.py", line 103, in delete
ctfd_1   |     Challenges.query.filter_by(id=challenge.id).delete()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3872, in delete
ctfd_1   |     delete_op.exec_()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
ctfd_1   |     self._do_exec()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1928, in _do_exec
ctfd_1   |     self._execute_stmt(delete_stmt)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
ctfd_1   |     self.result = self.query._execute_crud(stmt, self.mapper)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3514, in _execute_crud
ctfd_1   |     return conn.execute(stmt, self._params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
ctfd_1   |     return meth(self, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
ctfd_1   |     return connection._execute_clauseelement(self, multiparams, params)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
ctfd_1   |     distilled_params,
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1324, in _execute_context
ctfd_1   |     e, statement, parameters, cursor, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
ctfd_1   |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
ctfd_1   |     raise exception
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1284, in _execute_context
ctfd_1   |     cursor, statement, parameters, context
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
ctfd_1   |     cursor.execute(statement, parameters)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
ctfd_1   |     result = self._query(query)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
ctfd_1   |     conn.query(q)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
ctfd_1   |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
ctfd_1   |     result.read()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
ctfd_1   |     first_packet = self.connection._read_packet()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
ctfd_1   |     packet.check_error()
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
ctfd_1   |     err.raise_mysql_exception(self._data)
ctfd_1   |   File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
ctfd_1   |     raise errorclass(errno, errval)
ctfd_1   | sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`ctfd`.`docker_challenges`, CONSTRAINT `docker_challenges_ibfk_1` FOREIGN KEY (`id`) REFERENCES `challenges` (`id`))')
ctfd_1   | [SQL: DELETE FROM challenges WHERE challenges.id = %(id_1)s]
ctfd_1   | [parameters: {'id_1': 1}]
ctfd_1   | (Background on this error at: http://sqlalche.me/e/gkpj)
```

-------------------

according to https://stackoverflow.com/questions/1905470/cannot-delete-or-update-a-parent-row-a-foreign-key-constraint-fails  , it mentions to set `SET FOREIGN_KEY_CHECKS=0; -- to disable them `  . can this be set in the Python file?

**Comment by hitfzyangdianshi** [comment]
the problem disappears now
