### ISSUE TITLE
Course Grading Checkpoints are mandatory

### ISSUE THREAD

**Issue by robwaz** [pwncollege/dojo#162]
If a module used in a current "current course" does not have a "checkpoint" grading entry, the page returns error 500.

Trace of specific crash.
```
270391:1877799:ERROR [CTFd] Exception on /dojo/cse494-s2023/grades [GET]
270392-1877800-Traceback (most recent call last):
270393-1877801-  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
270394-1877802-    response = self.full_dispatch_request()
270395-1877803-  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
270396-1877804-    rv = self.handle_user_exception(e)
270397-1877805-  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
270398-1877806-    return original_handler(e)
270399-1877807-  File "/usr/local/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
270400-1877808-    return original_handler(e)
270401-1877809-  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
270402-1877810-    reraise(exc_type, exc_value, tb)
270403-1877811-  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
270404-1877812-    raise value
270405-1877813-  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
270406-1877814-    rv = self.dispatch_request()
270407-1877815-  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
270408-1877816-    return self.view_functions[rule.endpoint](**req.view_args)
270409-1877817-  File "/opt/CTFd/CTFd/plugins/dojo_plugin/utils/dojo/__init__.py", line 292, in wrapper
270410-1877818-    return func(*bound_args.args, **bound_args.kwargs)
270411-1877819-  File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 87, in authed_only_wrapper
270412-1877820-    return f(*args, **kwargs)
270413-1877821:  File "/opt/CTFd/CTFd/plugins/dojo_plugin/pages/grades.py", line 199, in view_grades
270414-1877822:    grades = next(grade(dojo, user))
270415-1877823:  File "/opt/CTFd/CTFd/plugins/dojo_plugin/pages/grades.py", line 175, in grade
270416-1877824-    int(checkpoint_solves),
270417-1877825-TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by robwaz** [comment]
This has been fixed, although I do not have the commit handy.
