### ISSUE TITLE
vscode extension error

### ISSUE THREAD

**Issue by Tim-Nosco** [pwncollege/dojo#51]
Hey Connor + team,

I'm having an issue where vscode `3.10.2` cant get the `ms-python.python` extension (Server returned 404). When I remove the version specification, the extension installs, but the next line that writes a python script fails. Related error below:

```
Mar 24 17:55:10 c41a6fe9d1eb docker-compose[3316]: Step 18/47 : RUN curl -fsSL https://code-server.dev/install.sh | /bin/sh /dev/stdin --version 3.10.2
Mar 24 17:55:10 c41a6fe9d1eb docker-compose[3316]:  ---> Using cache
Mar 24 17:55:10 c41a6fe9d1eb docker-compose[3316]:  ---> 95dcfb51fa92
Mar 24 17:55:10 c41a6fe9d1eb docker-compose[3316]: Step 19/47 : RUN mkdir -p /opt/code-server/extensions && code-server --extensions-dir=/opt/code-server/extensions --install-extension ms-python.python
Mar 24 17:55:10 c41a6fe9d1eb docker-compose[3316]:  ---> Running in 28ea96855e4a
Mar 24 17:55:10 c41a6fe9d1eb docker-compose[3316]: [2022-03-24T17:55:10.985Z] info  Wrote default config file to ~/.config/code-server/config.yaml
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]: Installing extensions...
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]: Server returned 404
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]: [2022-03-24T17:55:11.759Z] error vscode Failed Installing Extensions: ms-python.python
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]: [2022-03-24T17:55:11.761Z] error vscode Error: Failed Installing Extensions: ms-python.python
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]:     at O.installExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:19:42)
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]:     at async /usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:90861
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]:     at async M (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:94206)
Mar 24 17:55:11 c41a6fe9d1eb docker-compose[3316]:     at async process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:36:103823)
Mar 24 17:55:12 c41a6fe9d1eb docker-compose[3316]: The command '/bin/sh -c mkdir -p /opt/code-server/extensions && code-server --extensions-dir=/opt/code-server/extensions --install-extension ms-python.python' returned a non-zero code: 1
```

**Comment by Tim-Nosco** [comment]
Removing version in step 18 and removing step 20 allow the container to build.
